POST http://localhost:8080/api/v1/doctors HTTP/1.1
content-type: application/json

{
  "name": "Alberto Moncada",
  "specialties": ["5c0c153a-6793-4d00-bb63-2f8d2e418718", "59738048-889f-48b0-90af-e9ce2cde3a18"]
}

###
POST http://localhost:8080/api/v1/doctors HTTP/1.1
content-type: application/json

{
  "name": "Alberto Urbina",
  "specialties": ["5c0c153a-6793-4d00-bb63-2f8d2e418718"]
}

###
POST http://localhost:8080/api/v1/doctors HTTP/1.1
content-type: application/json

{
  "name": "Maria Luisa",
  "specialties": ["59738048-889f-48b0-90af-e9ce2cde3a18"]
}

###
GET http://localhost:8080/api/v1/doctors?specialty_id=5c0c153a-6793-4d00-bb63-2f8d2e418718 HTTP/1.1
content-type: application/json
